

# This file was *autogenerated* from the file computing_class_numbers.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import sys

# command line arguments
start = int(sys.argv[_sage_const_1 ])   # 1-based index
end   = int(sys.argv[_sage_const_2 ])

def process_disc(D):
    """
    Takes in a fundamental discriminant D and returns the class number.
    """
    return QuadraticField(D, "x").class_number()

with open("fundamental_discriminants.jsonl") as f:
    for idx, line in enumerate(f, start=_sage_const_1 ):  # idx = 1, 2, 3, ...
        if idx < start:
            continue
        if idx > end:
            break

        D = int(line.strip())  # raw integer -> discriminant
        result = process_disc(D)
        print(D, result)

