

# This file was *autogenerated* from the file testing_sage.sage
from sage.all_cmdline import *   # import sage library

from sage.libs.pari import pari

def process_disc_proven(D):
    bnf = pari(f"bnfinit(x^2 - {D}, 1)")
    return int(pari(f"bnf.clgp.no"))

print(process_disc_proven(int(input())))

